### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by duyuxuan** [CarGuo/gsy_github_app_flutter#583]
```
Reloaded 83 of 1338 libraries in 954ms.
E/flutter (10448): [ERROR:flutter/shell/common/shell.cc(178)] Dart Error: Unhandled exception:
E/flutter (10448): NoSuchMethodError: The getter 'currentLocalized' was called on null.
E/flutter (10448): Receiver: null
E/flutter (10448): Tried calling: currentLocalized
E/flutter (10448): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (10448): #1      GSYLocalizations.i18n (package:gsy_github_app_flutter/common/localization/default_localizations.dart:38:10)
E/flutter (10448): #2      _LoginPageState.build (package:gsy_github_app_flutter/page/login/login_page.dart:65:54)
E/flutter (10448): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
E/flutter (10448): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
E/flutter (10448): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (10448): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
E/flutter (10448): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (10448): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (10448): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
E/flutter (10448): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter (10448): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (10448): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (10448): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
E/flutter (10448): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter (10448): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter (10448): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter (10448): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter (10448): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (10448): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (10448): #28     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
E/flutter (10448): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (10448): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (10448): #32     StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
E/flutter (10448): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (10448): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (10448): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
E/flutter (10448): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
E/flutter (10448): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (10448): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (10448): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (10448): #42     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
E/flutter (10448): #43     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
E/flutter (10448): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:289

════════ (2) Exception caught by gesture ═══════════════════════════════════════════════════════════
The getter 'currentLocalized' was called on null.
Receiver: null
Tried calling: currentLocalized
════════════════════════════════════════════════════════════════════════════════════════════════════

```

Warning: This application's locale, ja_JP, is not supported by all of its localization delegates.

日文环境下项目无法启动

**Comment by CarGuo** [comment]
Android 还是 iOS ，模拟器环境 JP 还是真机？ 我这边没复现

**Comment by CarGuo** [comment]
复现了，如下图，因为语言的 isSupported 设置限制导致了  GSYLocalizations 获取 null

<img width="760" alt="image" src="https://user-images.githubusercontent.com/10770362/69597231-403e5680-1040-11ea-8217-462cb56c87f0.png">

**Comment by duyuxuan** [comment]
反应真神速，确实改完就可以启动了。感谢大神
