### ISSUE TITLE
如果出现登陆失败或者请求失败

### ISSUE THREAD

**Issue by CarGuo** [CarGuo/gsy_github_app_flutter#643]
1、确定你申请的 ClientId 和 ClientSecret 是正确的。

2、确定正常使用用户名密码登陆或者 OAuth 登陆。

3、Connection refused 的情况请更换网络环境。

**Comment by AngelSunpx** [comment]
![image](https://user-images.githubusercontent.com/12421932/76393040-af507880-63ad-11ea-80fd-bb87d7f051a1.png)

登录异常呢

**Comment by CarGuo** [comment]
> ![image](https://user-images.githubusercontent.com/12421932/76393040-af507880-63ad-11ea-80fd-bb87d7f051a1.png)
> 
> 登录异常呢

怎么样的异常？是自己编译的还是下载的

**Comment by AngelSunpx** [comment]
> > 登录异常呢
> 
> 怎么样的异常？是自己编译的还是下载的，442 可以换个网络环境试试

是自己编译的呢，挂VPN也试了，依然422

**Comment by CarGuo** [comment]
@AngelSunpx 推测是你申请的 github appid 和 appsercet 的问题，并且不要使用邮箱和密码登录，使用用户名和密码登录，或者授权登录。可以试试下载打包的 apk

**Comment by raorq** [comment]
> > > 登录异常呢
> > 
> > 
> > 怎么样的异常？是自己编译的还是下载的，442 可以换个网络环境试试
> 
> 是自己编译的呢，挂VPN也试了，依然422

我这边也是422，求助；

**Comment by raorq** [comment]
登陆异常提示422；
client_id等OK；
无论什么网络都是422

**Comment by raorq** [comment]
> @AngelSunpx 推测是你申请的 github appid 和 appsercet 的问题，并且不要使用邮箱和密码登录，使用用户名和密码登录，或者授权登录。可以试试下载打包的 apk

怎么去申请一个正确的appid呢？
 有教程吗？

**Comment by CarGuo** [comment]
@raorq 你用下载的app会吗？最近github 的dns和ssl部分区域是出现了问题。
id 在首页 readme 有教程

**Comment by raorq** [comment]
> @raorq 你用下载的app会吗？最近github 的dns和ssl部分区域是出现了问题。
> id 在首页 readme 有教程
> 
> 新版现在登录应该可以用授权登录了试试

是最新代码，还是你给的二维码下载的，我去下载一个看看；

**Comment by raorq** [comment]
最新code已经fix了，good!

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/101887324-a9572480-3bd7-11eb-9518-84cffc6c1906.png)

![image](https://user-images.githubusercontent.com/10770362/101887302-a0fee980-3bd7-11eb-97c6-06bfe91077ca.png)



## 如果出现如上图所示问题， `Authorize Carguo` 按键无法点击，那么一般是设备问题， Github 不支持当前浏览器，所以换个设备就可以了，只要在新的设备上授权完成，那么回到旧的设备也是可以正常登录。

## 正常登录如图所示

![image](https://user-images.githubusercontent.com/10770362/101887535-f804be80-3bd7-11eb-95c9-279e9e1ed2ed.png)

**Comment by ITmxs** [comment]
出现异常。
SocketException (SocketException: OS Error: Connection refused, errno = 111, address = avatars.githubusercontent.com, port = 45190)

**Comment by ITmxs** [comment]
请求异常信息: {"message":"Missing the 'notifications' scope.","documentation_url":"https://docs.github.com/rest/reference/activity#list-notifications-for-the-authenticated-user"}
D/CompatibilityChangeReporter(14872): Compat change id reported: 147798919; UID 10307; state: DISABLED

**Comment by CarGuo** [comment]
@ITmxs  SocketException 问题上面说了，然后 请求异常信息 没有复现

**Comment by helloworld10010** [comment]
tyoe null is not subtype of objectdefers

**Comment by CongYiMing** [comment]
请求信息异常如何处理啊

I/flutter (25350): 请求头: {content-type: application/json; charset=utf-8, Authorization: null}
W/ContentCatcher(25350): Failed to notify a WebView
E/InputMethodManager(25350): b/117267690: Failed to get fallback IMM with expected displayId=8 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{fcf75fb VFEDHVC.. ........ 0,0-1080,1191}
I/flutter (25350): 请求异常: DioError [DioErrorType.other]: type 'Null' is not a subtype of type 'Object'
I/flutter (25350): #0      DefaultHttpClientAdapter.fetch.<anonymous closure> (package:dio/src/adapters/io_adapter.dart:56:64)
I/flutter (25350): #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
I/flutter (25350): #2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:56:23)
I/flutter (25350): <asynchronous suspension>
I/flutter (25350): #3      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:625:22)
I/flutter (25350): <asynchronous suspension>
I/flutter (25350): #4      DioMixin.fetch._requestInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)

**Comment by CongYiMing** [comment]
> 请求信息异常如何处理啊
> 
> I/flutter (25350): 请求头: {content-type: application/json; charset=utf-8, Authorization: null}
> W/ContentCatcher(25350): Failed to notify a WebView
> E/InputMethodManager(25350): b/117267690: Failed to get fallback IMM with expected displayId=8 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{fcf75fb VFEDHVC.. ........ 0,0-1080,1191}
> I/flutter (25350): 请求异常: DioError [DioErrorType.other]: type 'Null' is not a subtype of type 'Object'
> I/flutter (25350): #0 DefaultHttpClientAdapter.fetch. (package:dio/src/adapters/io_adapter.dart:56:64)
> I/flutter (25350): #1 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
> I/flutter (25350): #2 DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:56:23)
> I/flutter (25350):
> I/flutter (25350): #3 DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:625:22)
> I/flutter (25350):
> I/flutter (25350): #4 DioMixin.fetch._requestInterceptorWrapper.... (package:dio/src/dio_mixin.dart)

我找到解决方案了
lib/common/net/interceptors/log_interceptor.dart:10
第23行添加如下代码
  options.headers.forEach((k, v) {
        if (v == null) {
          options.headers[k] = "";
        }
      });
![image](https://user-images.githubusercontent.com/6794085/111902523-d9d11900-8a78-11eb-9aa3-8da3e2d4f051.png)

**Comment by CongYiMing** [comment]
找到解决方案了
https://github.com/CarGuo/gsy_github_app_flutter/issues/643#issuecomment-803556246

**Comment by CaptXiong** [comment]
If you want the emulator use the VPN on your PC, try this: https://stackoverflow.com/questions/6943151/how-can-i-get-my-android-emulator-use-my-computers-vpn-interface/76684278#76684278

**Comment by tikon518** [comment]
报错“Assertion failed: file:///C:/Users/tikon/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/webview_flutter_platform_interface-2.6.0/lib/src/platform_webview_controller.dart:26:7
WebViewPlatform.instance != null
"A platform implementation for `webview_flutter` has not been set. Please ensure that an implementation of `WebViewPlatform` has been set to `WebViewPlatform.instance` before use. For unit testing, `WebViewPlatform.instance` can be set with your own test implementation."
 dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3             throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3              assertFailed
packages/webview_flutter_platform_interface/src/platform_webview_controller.dart 26:32  new
packages/webview_flutter/src/webview_controller.dart 101:11                             fromPlatformCreationParams
packages/gsy_github_app_flutter/page/login/login_webview.dart 40:36                     initState
packages/flutter/src/widgets/framework.dart 5611:55                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 6893:36                                     inflateWidget
packages/flutter/src/widgets/framework.dart 6905:32                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 6758:14                                     mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5462:5                                      [_firstBuild]
packages/flutter/src/widgets/framework.dart 5634:11                                     [_firstBuild]
packages/flutter/src/widgets/framework.dart 5456:5                                      mount
packages/flutter/src/widgets/framework.dart 4335:15                                     inflateWidget
packages/flutter/src/widgets/framework.dart 6893:36                                     inflateWidget
packages/flutter/src/widgets/framework.dart 3846:18                                     updateChild
packages/flutter/src/widgets/framework.dart 4033:32                                     updateChildren
packages/flutter/src/widgets/framework.dart 6918:17                                     update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5666:5                                      update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5809:5                                      update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5809:5                                      update
packages/flutter/src/widgets/inherited_notifier.dart 105:11                             update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5666:5                                      update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5809:5                                      update
packages/flutter/src/widgets/inherited_notifier.dart 105:11                             update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5666:5                                      update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5666:5                                      update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 6765:14                                     update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 6765:14                                     update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5809:5                                      update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 5809:5                                      update
packages/flutter/src/widgets/framework.dart 3824:14                                     updateChild
packages/flutter/src/widgets/framework.dart 5505:16                                     performRebuild
packages/flutter/src/widgets/framework.dart 5643:11                                     performRebuild
packages/flutter/src/widgets/framework.dart 5196:7                                      rebuild
packages/flutter/src/widgets/framework.dart 2904:18                                     buildScope
packages/flutter/src/widgets/binding.dart 989:9                                         drawFrame
packages/flutter/src/rendering/binding.dart 448:5                                       [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1386:7                                      [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1311:9                                      handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1169:5                                      [_handleDrawFrame]
dart-sdk/lib/async/zone.dart 1399:13                                                    _rootRun
dart-sdk/lib/async/zone.dart 1301:19                                                    run
dart-sdk/lib/async/zone.dart 1209:7                                                     runGuarded
lib/_engine/engine/platform_dispatcher.dart 1348:9                                      invoke
lib/_engine/engine/platform_dispatcher.dart 260:5                                       invokeOnDrawFrame
lib/_engine/engine/initialization.dart 185:36                                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37        _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39        dcall”

**Comment by tikon518** [comment]
帐号登录报这个：   ![image](https://github.com/CarGuo/gsy_github_app_flutter/assets/95847407/c6a1d156-0e33-4956-9856-5575812c86d8)
建议我安全登录：又报上面这个。

**Comment by CarGuo** [comment]
@tikon518  只支持 iOS 和 Android 平台

**Comment by tikon518** [comment]
意思  现在浏览器还不可以是吧？ 好的， 谢谢了。

**Comment by Johnsstt** [comment]
登录不进去啊！！！
![1722095979012](https://github.com/user-attachments/assets/f3554d32-9dbc-4341-8b98-1c4af103258a)

**Comment by wlyy460** [comment]
> 帐号登录报这个： ![image](https://github.com/CarGuo/gsy_github_app_flutter/assets/95847407/c6a1d156-0e33-4956-9856-5575812c86d8) 建议我安全登录：又报上面这个。

我也是这个问题

**Comment by CarGuo** [comment]
@wlyy460  使用授权登陆啊
