### ISSUE TITLE
授权登录异常

### ISSUE THREAD

**Issue by ff-frida** [CarGuo/gsy_github_app_flutter#712]
已经配置callback url。
appid和sc没有错误。
使用授权登录，账户密码正确的。然后点击授权。一直loading。以下是我的日志
```
/flutter (22669): 请求url：https://github.com/login/oauth/access_token?client_id=ab027e0b90aa61e6f39b&client_secret=f3a11c7ccd7cdc1659f6ddf021de2c7ce94120e8&code=8379254906422807f2c2
I/flutter (22669): 请求头: {content-type: application/json; charset=utf-8, Authorization: Basic ZmYtZnJpZGE6ZmFuZ2ZhbmcyMDIw}
W/ContentCatcher(22669): Failed to notify a WebView
E/BufferQueueProducer(22669): [SurfaceTexture-0-22669-1] dequeueBuffer: BufferQueue has been abandoned
E/chromium(22669): [ERROR:aw_browser_terminator.cc(125)] Renderer process (23881) crash detected (code -1).
I/flutter (22669): 返回参数: access_token=a9cabfa8db59441d2dbf7a16e9ce4017ce312adb&scope=&token_type=bearer
I/flutter (22669): #### access_token=a9cabfa8db59441d2dbf7a16e9ce4017ce312adb&scope=&token_type=bearer
I/flutter (22669): 请求url：https://api.github.com/user
I/flutter (22669): 请求头: {content-type: application/json; charset=utf-8, Authorization: Basic ZmYtZnJpZGE6ZmFuZ2ZhbmcyMDIw}
I/flutter (22669): 请求异常: DioError [DioErrorType.RESPONSE]: Http status error [401]
I/flutter (22669): 请求异常信息: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
I/flutter (22669): user result false
I/flutter (22669): Http status error [401]
I/flutter (22669): access_token=a9cabfa8db59441d2dbf7a16e9ce4017ce312adb&scope=&token_type=bearer
I/flutter (22669): type 'String' is not a subtype of type 'User'
I/flutter (22669): #0      UserDao.oauth (package:gsy_github_app_flutter/common/dao/user_dao.dart:53:54)
I/flutter (22669): <asynchronous suspension>
I/flutter (22669): #1      oauthEpic._loginIn (package:gsy_github_app_flutter/redux/login_redux.dart:93:29)
I/flutter (22669): <asynchronous suspension>
I/flutter (22669): #2      oauthEpic._loginIn (package:gsy_github_app_flutter/redux/login_redux.dart)
I/flutter (22669): #3      oauthEpic.<anonymous closure> (package:gsy_github_app_flutter/redux/login_redux.dart:99:38)
I/flutter (22669): #4      SwitchMapStreamTransformer._buildTransformer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/transformers/switch_map.dart:55:47)
I/flutter (22669): #5      _rootRunUnary (dart:async/zone.dart:1192:38)
I/flutter (22669): #6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
I/flutter (22669): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
I/flutter (22669): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
I/flutter (22669): #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
I/flutter (22669): #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
I/flutter (22669): #11     _Stre
```

代码是拉最新的无改动。
common中已经配置好我申请的key

**Comment by CarGuo** [comment]
Authorization: Basic ZmYtZnJpZGE6ZmFuZ2ZhbmcyMDIw 看起来是用了账号密码登录的模式，token 没有生效时候会走这个，你可以看 getAuthorization 方法，你是不是试过了账号密码登录的模式了？

用 web 登录是的话会走  LoginWebView ，然后在 navigationDelegate 中回调 code ，之后通过 oauthLogin 中的 OAuthAction 走到 oauthEpic 方法，进入UserDao 的  oauth  ，你看 TOKEN_KEY 是不是在这里正常保存了

**Comment by ff-frida** [comment]
非常感谢回答，正如你说的，我开始使用了账号密码登录，导致后面的问题。
现在账户密码模式，接口已经提示不支持了。都要走授权登录了。
我现在直接授权登录，可以正常进入了，感谢~
