### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Liway** [CarGuo/gsy_github_app_flutter#795]
Bad state: This is a Dart exception.
 #0      TrendPageState.build (package:gsy_github_app_flutter/page/trend/trend_page.dart:253:5)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#13     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#17     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#22     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#26     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#28     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1265:37)
#29     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1169:35)
#30     Iterable.forEach (dart:core/iterable.dart:325:35)
#31     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1213:24)
#32     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1146:7)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#37     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#38     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#40     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#41     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#42     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:237:11)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#53     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#55     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#61     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#67     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#72     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#76     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#89     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#95     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#96     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#99     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#100    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#101    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#105    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#108    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#110    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#116    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#123    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#126    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#127    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#128    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#131    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#132    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#136    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#139    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#140    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#141    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#144    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#145    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#146    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#148    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#150    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#153    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#155    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#158    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#160    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#163    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#164    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#165    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#166    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#168    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#169    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#172    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#173    StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#174    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#176    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#177    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#179    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#180    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#182    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#183    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#184    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#185    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#186    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#187    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#188    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#189    _rootRun (dart:async/zone.dart:1426:13)
#190    _CustomZone.run (dart:async/zone.dart:1328:19)
#191    _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#192    _invoke (dart:ui/hooks.dart:151:10)
#193    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#194    _drawFrame (dart:ui/hooks.dart:115:31)

**Comment by Liway** [comment]
你好！我已收到你的邮件，看后回复你。
