### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Liway** [CarGuo/gsy_github_app_flutter#796]
Bad state: This is a Dart exception.
 #0      TrendPageState.build (package:gsy_github_app_flutter/page/trend/trend_page.dart:253:5)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4968:11)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6215:14)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6215:14)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4968:11)
#33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#37     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#42     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1265:37)
#43     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1250:20)
#44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#45     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1242:12)
#46     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#47     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2025:59)
#48     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
#49     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2025:14)
#50     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#51     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:422:5)
#52     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:205:12)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#54     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#55     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#57     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#58     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#59     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#60     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#61     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#62     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#63     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#64     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#65     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#66     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#67     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#68     _rootRun (dart:async/zone.dart:1426:13)
#69     _CustomZone.run (dart:async/zone.dart:1328:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#71     _invoke (dart:ui/hooks.dart:151:10)
#72     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#73     _drawFrame (dart:ui/hooks.dart:115:31)

**Comment by Liway** [comment]
你好！我已收到你的邮件，看后回复你。
